### ISSUE TITLE
Archive this project?

### ISSUE THREAD

**Issue by Ash-Crow** [nasqueron/tasacora-server#11]
@dereckson @ramaneko shouldn't we archive (or even delete) this repository? It only had some initial configurations since it was created 6 years ago, except for a bump of Django version 2 years ago, but no actual code was ever produced.

While I find the idea behind the project interesting, it seems clear to me that none of us have either time or motivation to push through with the development of the tool, while the automated PRs to fix security issues are piling up.

**Comment by ramaneko** [comment]
No objection on my part. The project itself has potential I think, but it is not viable without a community, and I have no idea how to create one.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dereckson** [comment]
I concur with both statements.
